AllCops:
  TargetRubyVersion: 2.3

Metrics/BlockLength:
  Exclude:
    - '**/*.gemspec'
    - 'spec/**/*_spec.rb'

Metrics/ClassLength:
  Max: 120

Metrics/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 12

Style/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/AndOr:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/LambdaCall:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/VariableInterpolation:
  Enabled: false
